### ISSUE TITLE
Suport for Ethr-DID in React Native

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/react-native-uport-connect#1]

**Comment by Eseoghene** [comment]
2

**Comment by vongohren** [comment]
Is there any movement on this, now that there is a PR aswell?

**Comment by vongohren** [comment]
@simonas-notcat why is this blocked?

**Comment by simonas-notcat** [comment]
There are some issues with `uport-connect`. As soon as we solve them, I will update this library. If everything goes well, it should come out this week.

**Comment by vongohren** [comment]
@simonas-notcat cool cool!

**Comment by simonas-notcat** [comment]
New libs are out. Checkout new usage in https://github.com/uport-project/uport-react-native-demo
