### ISSUE TITLE
If you ever push this to testFlight, that example url schema is invalid

### ISSUE THREAD

**Issue by vongohren** [uport-project/react-native-uport-connect#12]
The current example of urlschema is invalid for testFlight.
I guess the solution to this is to just use anothe specific url schema?
Because it just depends on whatever that is configurated, and not anything app specific?

<img width="1083" alt="screenshot 2018-11-23 at 13 58 41" src="https://user-images.githubusercontent.com/1012055/48940271-04058100-ef28-11e8-85c3-84db1e0dcd2e.png">

**Comment by simonas-notcat** [comment]
@vongohren you are right. It was a bad idea to use just your app's MNID as `appUrlScheme`. I've updated README file to say that you need to use this format: `mnid{YOUR_DAPP_MNID}`
