### ISSUE TITLE
I would love to link to a native link and not https

### ISSUE THREAD

**Issue by vongohren** [uport-project/react-native-uport-connect#14]
**Is your feature request related to a problem? Please describe.**
Currently the uport-connect returns a https link, but that pops up a just once or always dialog on android because chrome can pick it up as well. Like the picture below. I would like to avoid this, then it would be possible to do something like this https://github.com/FiberJW/react-native-app-link/blob/master/index.js

![screenshot_20181201-171820](https://user-images.githubusercontent.com/1012055/49339927-fea3e700-f649-11e8-9a61-09c1dfdb6b7c.png)

**Describe the solution you'd like**
By having a native deeplink possibilit, the randomness of suddenly opening a browser with uport in it dissapears.

**Describe alternatives you've considered**
I am now checking if the app is there by checking can open url on "me.uport:"

**Comment by simonas-notcat** [comment]
Fixed in https://github.com/uport-project/react-native-uport-connect/pull/16
