### ISSUE TITLE
Uport-connect v1.0.0 integration request with react-native-uport-connect to support new features

### ISSUE THREAD

**Issue by kalirasu** [uport-project/react-native-uport-connect#8]
Dear Team,

Could you please advise, when we could expect new version of react-native-uport connect release with Uport-connect v1.0.0 version functionalities for mobile app integration ?

Thank you very much for your feedback.

Thanks,
Kaliraj S.M

**Comment by simonas-notcat** [comment]
We are trying to get it ready this week

**Comment by kalirasu** [comment]
Thanks @simonas-notcat for the release
