### ISSUE TITLE
[QUESTION] How to make sure uPort is installed on device

### ISSUE THREAD

**Issue by albertogiovanelli** [uport-project/react-native-uport-connect#9]
How can I handle the case when uPort is not installed on device? How can I catch the exception that is thrown from Linking.openUrl(url)?

**Comment by simonas-notcat** [comment]
This feature is now available in the latest release. To use it you need to add this to Info.plist
```
  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>me.uport</string>
  </array>
```

and then use `isUportAppInstalled()`
